// Generated by module-to-header; do not edit.
#pragma once

#include "lib/types.h"
#include <algorithm>
#include <cmath>
#include <limits>
#include <numbers>

namespace lib {
namespace math {
inline constexpr size MaxSize = std::numeric_limits<size>::max();
auto dist(auto a, auto b) {
        return std::abs(a - b);
    };
constexpr float64 rad2deg(float64 r) { return r * 180.0 / std::numbers::pi; };
constexpr float32 rad2deg(float32 r) { return r * float32(180.0 / std::numbers::pi); };
constexpr float64 deg2rad(float64 d) { return d * (std::numbers::pi / 180.0); };
constexpr float32 deg2rad(float32 d) { return d * float32(std::numbers::pi / 180.0); };
using std::max;
using std::min;
using std::abs;
using std::sqrt;
}
}
